name: Feature-Branch-Build

on:
  push:
    branches: [ "feature/**" ]
  workflow_dispatch:  # Allows manual triggering

permissions:
  contents: read  # Allows reading repository contents
  checks: write  # Allows writing test reports
  pull-requests: write  # Allows reporting results on PRs
  
jobs:
  build:
    uses: ./.github/workflows/build-template.yml
    with:
      node-version: '24'
      run-tests: true