name: Main-Branch-Build

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:  # Allows manual triggering
    inputs:
      release-powerplatform-solution:
        required: false
        type: boolean
        default: false
        description: 'Release Power Platform solution'
        
permissions:
  contents: read  # Allows reading repository contents
  checks: write  # Allows writing test reports
  pull-requests: write  # Allows reporting results on PRs
  
jobs:
  build:
    uses: ./.github/workflows/build-template.yml
    with:
      node-version: '24'
      run-tests: true
      build-powerplatform-solution: true

  # Additional job that extends the base build
  deploy:
    if: ${{ inputs.release-powerplatform-solution == 'true' }}
    needs: build
    uses: ./.github/workflows/release-template.yml
    with:
      target-dataverse-url: ${{ vars.DATAVERSE_TARGET_URL }}